/**
 *
 *  Teacherassignment.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Teacherassignment.h"
#include "Assignment.h"
#include "Teacher.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::educloud;

const std::string Teacherassignment::Cols::_TeacherId = "\"TeacherId\"";
const std::string Teacherassignment::Cols::_AssignmentId = "\"AssignmentId\"";
const std::vector<std::string> Teacherassignment::primaryKeyName = {"TeacherId","AssignmentId"};
const bool Teacherassignment::hasPrimaryKey = true;
const std::string Teacherassignment::tableName = "\"TeacherAssignment\"";

const std::vector<typename Teacherassignment::MetaData> Teacherassignment::metaData_={
{"TeacherId","std::string","uuid",0,0,1,1},
{"AssignmentId","std::string","uuid",0,0,1,1}
};
const std::string &Teacherassignment::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Teacherassignment::Teacherassignment(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["TeacherId"].isNull())
        {
            teacherid_=std::make_shared<std::string>(r["TeacherId"].as<std::string>());
        }
        if(!r["AssignmentId"].isNull())
        {
            assignmentid_=std::make_shared<std::string>(r["AssignmentId"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            teacherid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            assignmentid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Teacherassignment::Teacherassignment(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            teacherid_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            assignmentid_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

Teacherassignment::Teacherassignment(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("TeacherId"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["TeacherId"].isNull())
        {
            teacherid_=std::make_shared<std::string>(pJson["TeacherId"].asString());
        }
    }
    if(pJson.isMember("AssignmentId"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["AssignmentId"].isNull())
        {
            assignmentid_=std::make_shared<std::string>(pJson["AssignmentId"].asString());
        }
    }
}

void Teacherassignment::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            teacherid_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            assignmentid_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void Teacherassignment::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("TeacherId"))
    {
        if(!pJson["TeacherId"].isNull())
        {
            teacherid_=std::make_shared<std::string>(pJson["TeacherId"].asString());
        }
    }
    if(pJson.isMember("AssignmentId"))
    {
        if(!pJson["AssignmentId"].isNull())
        {
            assignmentid_=std::make_shared<std::string>(pJson["AssignmentId"].asString());
        }
    }
}

const std::string &Teacherassignment::getValueOfTeacherid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(teacherid_)
        return *teacherid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Teacherassignment::getTeacherid() const noexcept
{
    return teacherid_;
}
void Teacherassignment::setTeacherid(const std::string &pTeacherid) noexcept
{
    teacherid_ = std::make_shared<std::string>(pTeacherid);
    dirtyFlag_[0] = true;
}
void Teacherassignment::setTeacherid(std::string &&pTeacherid) noexcept
{
    teacherid_ = std::make_shared<std::string>(std::move(pTeacherid));
    dirtyFlag_[0] = true;
}

const std::string &Teacherassignment::getValueOfAssignmentid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(assignmentid_)
        return *assignmentid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Teacherassignment::getAssignmentid() const noexcept
{
    return assignmentid_;
}
void Teacherassignment::setAssignmentid(const std::string &pAssignmentid) noexcept
{
    assignmentid_ = std::make_shared<std::string>(pAssignmentid);
    dirtyFlag_[1] = true;
}
void Teacherassignment::setAssignmentid(std::string &&pAssignmentid) noexcept
{
    assignmentid_ = std::make_shared<std::string>(std::move(pAssignmentid));
    dirtyFlag_[1] = true;
}

void Teacherassignment::updateId(const uint64_t id)
{
}
typename Teacherassignment::PrimaryKeyType Teacherassignment::getPrimaryKey() const
{
    return std::make_tuple(*teacherid_,*assignmentid_);
}

const std::vector<std::string> &Teacherassignment::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "TeacherId",
        "AssignmentId"
    };
    return inCols;
}

void Teacherassignment::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getTeacherid())
        {
            binder << getValueOfTeacherid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getAssignmentid())
        {
            binder << getValueOfAssignmentid();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Teacherassignment::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void Teacherassignment::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getTeacherid())
        {
            binder << getValueOfTeacherid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getAssignmentid())
        {
            binder << getValueOfAssignmentid();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Teacherassignment::toJson() const
{
    Json::Value ret;
    if(getTeacherid())
    {
        ret["TeacherId"]=getValueOfTeacherid();
    }
    else
    {
        ret["TeacherId"]=Json::Value();
    }
    if(getAssignmentid())
    {
        ret["AssignmentId"]=getValueOfAssignmentid();
    }
    else
    {
        ret["AssignmentId"]=Json::Value();
    }
    return ret;
}

Json::Value Teacherassignment::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getTeacherid())
            {
                ret[pMasqueradingVector[0]]=getValueOfTeacherid();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getAssignmentid())
            {
                ret[pMasqueradingVector[1]]=getValueOfAssignmentid();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getTeacherid())
    {
        ret["TeacherId"]=getValueOfTeacherid();
    }
    else
    {
        ret["TeacherId"]=Json::Value();
    }
    if(getAssignmentid())
    {
        ret["AssignmentId"]=getValueOfAssignmentid();
    }
    else
    {
        ret["AssignmentId"]=Json::Value();
    }
    return ret;
}

bool Teacherassignment::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("TeacherId"))
    {
        if(!validJsonOfField(0, "TeacherId", pJson["TeacherId"], err, true))
            return false;
    }
    else
    {
        err="The TeacherId column cannot be null";
        return false;
    }
    if(pJson.isMember("AssignmentId"))
    {
        if(!validJsonOfField(1, "AssignmentId", pJson["AssignmentId"], err, true))
            return false;
    }
    else
    {
        err="The AssignmentId column cannot be null";
        return false;
    }
    return true;
}
bool Teacherassignment::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Teacherassignment::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("TeacherId"))
    {
        if(!validJsonOfField(0, "TeacherId", pJson["TeacherId"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("AssignmentId"))
    {
        if(!validJsonOfField(1, "AssignmentId", pJson["AssignmentId"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool Teacherassignment::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                         const std::vector<std::string> &pMasqueradingVector,
                                                         std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Teacherassignment::validJsonOfField(size_t index,
                                         const std::string &fieldName,
                                         const Json::Value &pJson,
                                         std::string &err,
                                         bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Assignment Teacherassignment::getAssignment(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from Assignment where Id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *assignmentid_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Assignment(r[0]);
}

void Teacherassignment::getAssignment(const DbClientPtr &clientPtr,
                                      const std::function<void(Assignment)> &rcb,
                                      const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from Assignment where Id = $1";
    *clientPtr << sql
               << *assignmentid_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Assignment(r[0]));
                    }
               }
               >> ecb;
}
Teacher Teacherassignment::getTeacher(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from Teacher where Id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *teacherid_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Teacher(r[0]);
}

void Teacherassignment::getTeacher(const DbClientPtr &clientPtr,
                                   const std::function<void(Teacher)> &rcb,
                                   const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from Teacher where Id = $1";
    *clientPtr << sql
               << *teacherid_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Teacher(r[0]));
                    }
               }
               >> ecb;
}
