/**
 *
 *  Teachersubject.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Teachersubject.h"
#include "Subject.h"
#include "Teacher.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::educloud;

const std::string Teachersubject::Cols::_TeacherId = "\"TeacherId\"";
const std::string Teachersubject::Cols::_SubjectId = "\"SubjectId\"";
const std::vector<std::string> Teachersubject::primaryKeyName = {"TeacherId","SubjectId"};
const bool Teachersubject::hasPrimaryKey = true;
const std::string Teachersubject::tableName = "\"TeacherSubject\"";

const std::vector<typename Teachersubject::MetaData> Teachersubject::metaData_={
{"TeacherId","std::string","uuid",0,0,1,1},
{"SubjectId","std::string","uuid",0,0,1,1}
};
const std::string &Teachersubject::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Teachersubject::Teachersubject(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["TeacherId"].isNull())
        {
            teacherid_=std::make_shared<std::string>(r["TeacherId"].as<std::string>());
        }
        if(!r["SubjectId"].isNull())
        {
            subjectid_=std::make_shared<std::string>(r["SubjectId"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            teacherid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            subjectid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Teachersubject::Teachersubject(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            teacherid_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            subjectid_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

Teachersubject::Teachersubject(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("TeacherId"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["TeacherId"].isNull())
        {
            teacherid_=std::make_shared<std::string>(pJson["TeacherId"].asString());
        }
    }
    if(pJson.isMember("SubjectId"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["SubjectId"].isNull())
        {
            subjectid_=std::make_shared<std::string>(pJson["SubjectId"].asString());
        }
    }
}

void Teachersubject::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            teacherid_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            subjectid_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void Teachersubject::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("TeacherId"))
    {
        if(!pJson["TeacherId"].isNull())
        {
            teacherid_=std::make_shared<std::string>(pJson["TeacherId"].asString());
        }
    }
    if(pJson.isMember("SubjectId"))
    {
        if(!pJson["SubjectId"].isNull())
        {
            subjectid_=std::make_shared<std::string>(pJson["SubjectId"].asString());
        }
    }
}

const std::string &Teachersubject::getValueOfTeacherid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(teacherid_)
        return *teacherid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Teachersubject::getTeacherid() const noexcept
{
    return teacherid_;
}
void Teachersubject::setTeacherid(const std::string &pTeacherid) noexcept
{
    teacherid_ = std::make_shared<std::string>(pTeacherid);
    dirtyFlag_[0] = true;
}
void Teachersubject::setTeacherid(std::string &&pTeacherid) noexcept
{
    teacherid_ = std::make_shared<std::string>(std::move(pTeacherid));
    dirtyFlag_[0] = true;
}

const std::string &Teachersubject::getValueOfSubjectid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(subjectid_)
        return *subjectid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Teachersubject::getSubjectid() const noexcept
{
    return subjectid_;
}
void Teachersubject::setSubjectid(const std::string &pSubjectid) noexcept
{
    subjectid_ = std::make_shared<std::string>(pSubjectid);
    dirtyFlag_[1] = true;
}
void Teachersubject::setSubjectid(std::string &&pSubjectid) noexcept
{
    subjectid_ = std::make_shared<std::string>(std::move(pSubjectid));
    dirtyFlag_[1] = true;
}

void Teachersubject::updateId(const uint64_t id)
{
}
typename Teachersubject::PrimaryKeyType Teachersubject::getPrimaryKey() const
{
    return std::make_tuple(*teacherid_,*subjectid_);
}

const std::vector<std::string> &Teachersubject::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "TeacherId",
        "SubjectId"
    };
    return inCols;
}

void Teachersubject::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getTeacherid())
        {
            binder << getValueOfTeacherid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getSubjectid())
        {
            binder << getValueOfSubjectid();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Teachersubject::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void Teachersubject::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getTeacherid())
        {
            binder << getValueOfTeacherid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getSubjectid())
        {
            binder << getValueOfSubjectid();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Teachersubject::toJson() const
{
    Json::Value ret;
    if(getTeacherid())
    {
        ret["TeacherId"]=getValueOfTeacherid();
    }
    else
    {
        ret["TeacherId"]=Json::Value();
    }
    if(getSubjectid())
    {
        ret["SubjectId"]=getValueOfSubjectid();
    }
    else
    {
        ret["SubjectId"]=Json::Value();
    }
    return ret;
}

Json::Value Teachersubject::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getTeacherid())
            {
                ret[pMasqueradingVector[0]]=getValueOfTeacherid();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getSubjectid())
            {
                ret[pMasqueradingVector[1]]=getValueOfSubjectid();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getTeacherid())
    {
        ret["TeacherId"]=getValueOfTeacherid();
    }
    else
    {
        ret["TeacherId"]=Json::Value();
    }
    if(getSubjectid())
    {
        ret["SubjectId"]=getValueOfSubjectid();
    }
    else
    {
        ret["SubjectId"]=Json::Value();
    }
    return ret;
}

bool Teachersubject::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("TeacherId"))
    {
        if(!validJsonOfField(0, "TeacherId", pJson["TeacherId"], err, true))
            return false;
    }
    else
    {
        err="The TeacherId column cannot be null";
        return false;
    }
    if(pJson.isMember("SubjectId"))
    {
        if(!validJsonOfField(1, "SubjectId", pJson["SubjectId"], err, true))
            return false;
    }
    else
    {
        err="The SubjectId column cannot be null";
        return false;
    }
    return true;
}
bool Teachersubject::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Teachersubject::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("TeacherId"))
    {
        if(!validJsonOfField(0, "TeacherId", pJson["TeacherId"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("SubjectId"))
    {
        if(!validJsonOfField(1, "SubjectId", pJson["SubjectId"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool Teachersubject::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Teachersubject::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Subject Teachersubject::getSubject(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from Subject where Id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *subjectid_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Subject(r[0]);
}

void Teachersubject::getSubject(const DbClientPtr &clientPtr,
                                const std::function<void(Subject)> &rcb,
                                const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from Subject where Id = $1";
    *clientPtr << sql
               << *subjectid_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Subject(r[0]));
                    }
               }
               >> ecb;
}
Teacher Teachersubject::getTeacher(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from Teacher where Id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *teacherid_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Teacher(r[0]);
}

void Teachersubject::getTeacher(const DbClientPtr &clientPtr,
                                const std::function<void(Teacher)> &rcb,
                                const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from Teacher where Id = $1";
    *clientPtr << sql
               << *teacherid_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Teacher(r[0]));
                    }
               }
               >> ecb;
}
